### ISSUE TITLE
How to install ROPTLIB on Ubuntu

### ISSUE THREAD

**Issue by limeng1523** [whuang08/ROPTLIB#15]
Thanks for your works!
I'm trying to use ROPTLIB on Ubuntu 18.04 with c++. Now I have complied the code and getted a shared library, but I don't know if I got the right shared library. Besides, I also don't know how to install ROPTLIB to my computer. This is not mentioned in user manual. Could you tell me how can I install it? Thank you very much!

**Comment by whuang08** [comment]
Hi,
Since you mentioned a shared library, I suspect that you want to run ROPTLIB in C++ environment.
First, go to the directory of ROPTLIB and use the commend
>>make ROPTLIB TP=name_of_the_test_file
to generate a binary file for a test problem.
Then run the generated binary file to see the test results.

A more detailed instruction for compiling the code and running an example is given in the section 2.3 of the user manual.

I hope I answered your question. 
Let me know if you still have questions.

Best,
Wen

**Comment by limeng1523** [comment]
Hi,
Thanks for your answer. I still don't know how to install ROPTLIB to my computer. When I use find_package in CMakeLists, cmake can not find ROPTLIB. If you can tell me how to use ROPTLIB in CMakelists, that will be great. Thank you very much.

**Comment by whuang08** [comment]
Hi,
ROPTLIB has its makefile. Therefore, you can use /makefile command in the directory of ROPTLIB.

The detailed steps to set up the latest version of ROPTLIB in terminal are:
1. Install BLAS, LAPACK and FFTW:
	sudo apt-get install build-essential
	sudo apt-get install liblapack*
	sudo apt-get install libblas*
	sudo apt-get install libfftw3*
2. Download the latest version of ROPTLIB and go the the directory of ROPTLIB.
3. Run Makefile to generate a binary file for a test problem, i.e., using the command:
        make ROPTLIB TP=DriverCpp
4. Run ./DriverCpp to see the test results for ./test/DriverCpp.cpp.

Best,

Wen

**Comment by limeng1523** [comment]
Thanks for your answer. I have resolved my problems. Thank you very much!
